name: Package for Linux

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Package Application
      uses: action-python/pyinstaller-py3.8@amd64
      with:
        path: .

    - uses: actions/upload-artifact@v2
      with:
        name: name-of-artifact
        path: src/dist/linux