name: Package for Windows

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    branches: [main]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Package Application
      uses: tevenfeng/Pyinstaller-docker@win64
      with:
        path: .

    - uses: actions/upload-artifact@v2
      with:
        name: winfred_win
        path: dist/windows